services:
  server:
    container_name: personal-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
    environment:
      - PORT=5000
      # - ORIGIN="https://joshbruegger.com"

networks:
  default:
    name: caddy_internal
    external: true
